---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_TAILSCALE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:AVYdlBXZTtX4DloVyaEr638=,iv:qN9U7gIYnY+d7DjiGFYNcu/ab3yLIxMYLscAWYUONjQ=,tag:dkvlhg2+mFVHSA6h9MuwvQ==,type:str]
  SECRET_TAILSCALE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:vs3tb2+ldVBS3BS2Ubw3H66K5vTRIESR7npg1pJoKVj1ohrjMgwjFzuVHXnCDQgBLN0fawAPG9VqzPjMrS4bFQ==,iv:QNFYkul2yKiLK8ZStkOSLXwbhMQr0rAxn/XbZDM1K8E=,tag:HWCwC8RTVhVJHjoBT27Yyw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdUlXcG1wRlU1MGVzbTVy
        b0plL0p3eE9pVHlJM3BhRHhnMDJzOUM4L0gwCmg0eWw4ZDdnbW8rVmYvTlhIU2VC
        d3IvTE9ybHBGa0x2N3BhQzdlK0NaUmcKLS0tIG5udjgvVlYxUXR6aUFCTWNXRmlP
        ZVozNjVvODUwVGtXelpGbWRIUzh1QmsKI9TeJvADp7sPS0W+pCBIE3aQTeR+aNDW
        T/cyOPt8pCy3DR5+4Z9tGvu0ajG68RzxD3BocyLtXnUSSq45ix9AHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mx87j4jfznc8t4dlu25myh3ugdam4df20xj3l9jdy7n9jlc9my6sx9cx6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T01:58:46Z"
  mac: ENC[AES256_GCM,data:1+91Bc7BaVzmyWqh2QM0RNcWemure8JPWVZlic9Ur2VrHx4Rfo6/pqrVOYlH7bJWERD55FnLxLtqN4jbXnf3qnIAWgknMCUH68kXcNmBwUb/pITE5yWr5xzZGbF7L/WWhOVFQx8qKInzPzEEEvG0m2GhaUbKKexvvYAgafq374s=,iv:M4tymZ75tVgFARFCIqvc5Jg5D1LuHxhGKL3KzXMCEI0=,tag:+abLl/mwvAJ21ZGS+u+3oA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
