---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: home-assistant
  interval: 1h
  values:
    controllers:
      home-assistant:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2026.6.0
            env:
              TZ: America/Chicago
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8123
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 6
              readiness: *probes
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                memory: 2Gi
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /config
