---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  chartRef:
    kind: OCIRepository
    name: mealie
  interval: 1h
  values:
    controllers:
      mealie:
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.19.2
            env:
              TZ: America/Chicago
              BASE_URL: https://meal.tailnet.ts.net
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 9000
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 6
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: mealie
        ports:
          http:
            port: 9000
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /app/data
